root: true
env:
  browser: true
  node: true
parserOptions:
  parser: babel-eslint
extends:
- eslint:recommended
- plugin:vue/essential
plugins:
- vue
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  no-console: warn
  comma-dangle:
    - warn
    - always-multiline
