root: true
globals:
  artifacts: false
  contract: false
  assert: false
env:
  browser: true
  node: true
  mocha: true
parserOptions:
  parser: babel-eslint
  sourceType: module
  allowImportExportEverywhere: true
  ecmaVersion: 2017
extends:
- eslint:recommended
- plugin:vue/recommended
plugins:
- vue
- sort-imports-es6-autofix
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  no-console:
    - off
  comma-dangle:
    - warn
    - functions: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      arrays: always-multiline
  object-curly-spacing:
    - warn
    - always
    - arraysInObjects: true
      objectsInObjects: true
  no-unused-vars:
    - warn
    - args: none
  max-len:
    - warn
    - 80
    - ignoreStrings: true
  sort-imports-es6-autofix/sort-imports-es6:
    - warn
    - ignoreCase: false
      ignoreMemberSort: false
      memberSyntaxSortOrder: ["none", "all", "multiple", "single"]
