root: true
globals:
  artifacts: false
  contract: false
  assert: false
env:
  browser: true
  node: true
  mocha: true
parserOptions:
  parser: babel-eslint
  sourceType: module
  allowImportExportEverywhere: true
  ecmaVersion: 2017
extends:
- eslint:recommended
- plugin:vue/recommended
plugins:
- vue
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
  no-console: warn
  comma-dangle:
    - warn
    - always-multiline
  no-unused-vars:
    - warn
