env:
  es6: true
  node: true
  mocha: true
globals:
  artifacts: false
  contract: false
  assert: false
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
